# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: driver/v1/node_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'driver/v1/node_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from driver.v1 import types_pb2 as driver_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x64river/v1/node_service.proto\x12\x13nodeplane.driver.v1\x1a\x15\x64river/v1/types.proto\"-\n\x19GetNodeDiagnosticsRequest\x12\x10\n\x08node_key\x18\x01 \x01(\t\"s\n\x1aGetNodeDiagnosticsResponse\x12\x10\n\x08node_key\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\x32\n\x05items\x18\x03 \x03(\x0b\x32#.nodeplane.driver.v1.DiagnosticItem\"-\n\x19InspectBackendNodeRequest\x12\x10\n\x08node_key\x18\x01 \x01(\t\"\xd7\x01\n\x16\x42\x61\x63kendNodeObservation\x12\x10\n\x08node_key\x18\x01 \x01(\t\x12\x14\n\x0chealth_state\x18\x02 \x01(\t\x12\x17\n\x0fruntime_version\x18\x03 \x01(\t\x12\x16\n\x0eruntime_commit\x18\x04 \x01(\t\x12\x1b\n\x13xray_config_present\x18\x05 \x01(\x08\x12\x1a\n\x12\x61wg_config_present\x18\x06 \x01(\x08\x12\x15\n\ragent_version\x18\x07 \x01(\t\x12\x14\n\x0c\x61gent_commit\x18\x08 \x01(\t2\xf7\x01\n\x0bNodeService\x12u\n\x12GetNodeDiagnostics\x12..nodeplane.driver.v1.GetNodeDiagnosticsRequest\x1a/.nodeplane.driver.v1.GetNodeDiagnosticsResponse\x12q\n\x12InspectBackendNode\x12..nodeplane.driver.v1.InspectBackendNodeRequest\x1a+.nodeplane.driver.v1.BackendNodeObservationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver.v1.node_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETNODEDIAGNOSTICSREQUEST']._serialized_start=76
  _globals['_GETNODEDIAGNOSTICSREQUEST']._serialized_end=121
  _globals['_GETNODEDIAGNOSTICSRESPONSE']._serialized_start=123
  _globals['_GETNODEDIAGNOSTICSRESPONSE']._serialized_end=238
  _globals['_INSPECTBACKENDNODEREQUEST']._serialized_start=240
  _globals['_INSPECTBACKENDNODEREQUEST']._serialized_end=285
  _globals['_BACKENDNODEOBSERVATION']._serialized_start=288
  _globals['_BACKENDNODEOBSERVATION']._serialized_end=503
  _globals['_NODESERVICE']._serialized_start=506
  _globals['_NODESERVICE']._serialized_end=753
# @@protoc_insertion_point(module_scope)
