# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from driver.v1 import node_service_pb2 as driver_dot_v1_dot_node__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in driver/v1/node_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNodeDiagnostics = channel.unary_unary(
                '/nodeplane.driver.v1.NodeService/GetNodeDiagnostics',
                request_serializer=driver_dot_v1_dot_node__service__pb2.GetNodeDiagnosticsRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_node__service__pb2.GetNodeDiagnosticsResponse.FromString,
                _registered_method=True)
        self.InspectBackendNode = channel.unary_unary(
                '/nodeplane.driver.v1.NodeService/InspectBackendNode',
                request_serializer=driver_dot_v1_dot_node__service__pb2.InspectBackendNodeRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_node__service__pb2.BackendNodeObservation.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNodeDiagnostics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectBackendNode(self, request, context):
        """Backend-owned read path: only the configured agent target is consulted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNodeDiagnostics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeDiagnostics,
                    request_deserializer=driver_dot_v1_dot_node__service__pb2.GetNodeDiagnosticsRequest.FromString,
                    response_serializer=driver_dot_v1_dot_node__service__pb2.GetNodeDiagnosticsResponse.SerializeToString,
            ),
            'InspectBackendNode': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectBackendNode,
                    request_deserializer=driver_dot_v1_dot_node__service__pb2.InspectBackendNodeRequest.FromString,
                    response_serializer=driver_dot_v1_dot_node__service__pb2.BackendNodeObservation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nodeplane.driver.v1.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nodeplane.driver.v1.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNodeDiagnostics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.NodeService/GetNodeDiagnostics',
            driver_dot_v1_dot_node__service__pb2.GetNodeDiagnosticsRequest.SerializeToString,
            driver_dot_v1_dot_node__service__pb2.GetNodeDiagnosticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectBackendNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.NodeService/InspectBackendNode',
            driver_dot_v1_dot_node__service__pb2.InspectBackendNodeRequest.SerializeToString,
            driver_dot_v1_dot_node__service__pb2.BackendNodeObservation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
