# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from driver.v1 import provisioning_service_pb2 as driver_dot_v1_dot_provisioning__service__pb2
from driver.v1 import types_pb2 as driver_dot_v1_dot_types__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in driver/v1/provisioning_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProvisioningServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveProfileIntent = channel.unary_unary(
                '/nodeplane.driver.v1.ProvisioningService/ResolveProfileIntent',
                request_serializer=driver_dot_v1_dot_provisioning__service__pb2.ApplyProfileIntentRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_provisioning__service__pb2.ProfileInspection.FromString,
                _registered_method=True)
        self.RecoverProfileIntent = channel.unary_unary(
                '/nodeplane.driver.v1.ProvisioningService/RecoverProfileIntent',
                request_serializer=driver_dot_v1_dot_provisioning__service__pb2.ApplyProfileIntentRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_provisioning__service__pb2.RecoverProfileIntentResponse.FromString,
                _registered_method=True)
        self.InspectProfileIntent = channel.unary_unary(
                '/nodeplane.driver.v1.ProvisioningService/InspectProfileIntent',
                request_serializer=driver_dot_v1_dot_provisioning__service__pb2.ApplyProfileIntentRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_provisioning__service__pb2.ProfileInspection.FromString,
                _registered_method=True)
        self.ApplyProfileIntent = channel.unary_unary(
                '/nodeplane.driver.v1.ProvisioningService/ApplyProfileIntent',
                request_serializer=driver_dot_v1_dot_provisioning__service__pb2.ApplyProfileIntentRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
                _registered_method=True)


class ProvisioningServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ResolveProfileIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecoverProfileIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectProfileIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyProfileIntent(self, request, context):
        """Explicit backend-owned intent. Never reads legacy business tables.
        x-node-plane-command-id is mandatory and must remain stable on retries.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProvisioningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveProfileIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveProfileIntent,
                    request_deserializer=driver_dot_v1_dot_provisioning__service__pb2.ApplyProfileIntentRequest.FromString,
                    response_serializer=driver_dot_v1_dot_provisioning__service__pb2.ProfileInspection.SerializeToString,
            ),
            'RecoverProfileIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.RecoverProfileIntent,
                    request_deserializer=driver_dot_v1_dot_provisioning__service__pb2.ApplyProfileIntentRequest.FromString,
                    response_serializer=driver_dot_v1_dot_provisioning__service__pb2.RecoverProfileIntentResponse.SerializeToString,
            ),
            'InspectProfileIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectProfileIntent,
                    request_deserializer=driver_dot_v1_dot_provisioning__service__pb2.ApplyProfileIntentRequest.FromString,
                    response_serializer=driver_dot_v1_dot_provisioning__service__pb2.ProfileInspection.SerializeToString,
            ),
            'ApplyProfileIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyProfileIntent,
                    request_deserializer=driver_dot_v1_dot_provisioning__service__pb2.ApplyProfileIntentRequest.FromString,
                    response_serializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nodeplane.driver.v1.ProvisioningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nodeplane.driver.v1.ProvisioningService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProvisioningService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ResolveProfileIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.ProvisioningService/ResolveProfileIntent',
            driver_dot_v1_dot_provisioning__service__pb2.ApplyProfileIntentRequest.SerializeToString,
            driver_dot_v1_dot_provisioning__service__pb2.ProfileInspection.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecoverProfileIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.ProvisioningService/RecoverProfileIntent',
            driver_dot_v1_dot_provisioning__service__pb2.ApplyProfileIntentRequest.SerializeToString,
            driver_dot_v1_dot_provisioning__service__pb2.RecoverProfileIntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectProfileIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.ProvisioningService/InspectProfileIntent',
            driver_dot_v1_dot_provisioning__service__pb2.ApplyProfileIntentRequest.SerializeToString,
            driver_dot_v1_dot_provisioning__service__pb2.ProfileInspection.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyProfileIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.ProvisioningService/ApplyProfileIntent',
            driver_dot_v1_dot_provisioning__service__pb2.ApplyProfileIntentRequest.SerializeToString,
            driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
