# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: driver/v1/provisioning_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'driver/v1/provisioning_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from driver.v1 import types_pb2 as driver_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$driver/v1/provisioning_service.proto\x12\x13nodeplane.driver.v1\x1a\x15\x64river/v1/types.proto\"4\n\x1cRecoverProfileIntentResponse\x12\x14\n\x0cpayload_json\x18\x01 \x01(\t\"s\n\x11ProfileInspection\x12\x14\n\x0c\x64isk_present\x18\x01 \x01(\x08\x12\x14\n\x0clive_present\x18\x02 \x01(\x08\x12\x18\n\x10identity_matches\x18\x03 \x01(\x08\x12\x18\n\x10\x63onfig_available\x18\x04 \x01(\x08\"\xb1\x01\n\x19\x41pplyProfileIntentRequest\x12\x10\n\x08node_key\x18\x01 \x01(\t\x12\x14\n\x0cruntime_name\x18\x02 \x01(\t\x12\x15\n\rprotocol_kind\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\x12\x18\n\x10\x64\x65sired_revision\x18\x05 \x01(\x04\x12+\n\x04xray\x18\x06 \x01(\x0b\x32\x1d.nodeplane.driver.v1.XraySpec2\xe3\x03\n\x13ProvisioningService\x12n\n\x14ResolveProfileIntent\x12..nodeplane.driver.v1.ApplyProfileIntentRequest\x1a&.nodeplane.driver.v1.ProfileInspection\x12y\n\x14RecoverProfileIntent\x12..nodeplane.driver.v1.ApplyProfileIntentRequest\x1a\x31.nodeplane.driver.v1.RecoverProfileIntentResponse\x12n\n\x14InspectProfileIntent\x12..nodeplane.driver.v1.ApplyProfileIntentRequest\x1a&.nodeplane.driver.v1.ProfileInspection\x12q\n\x12\x41pplyProfileIntent\x12..nodeplane.driver.v1.ApplyProfileIntentRequest\x1a+.nodeplane.driver.v1.StartOperationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver.v1.provisioning_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOVERPROFILEINTENTRESPONSE']._serialized_start=84
  _globals['_RECOVERPROFILEINTENTRESPONSE']._serialized_end=136
  _globals['_PROFILEINSPECTION']._serialized_start=138
  _globals['_PROFILEINSPECTION']._serialized_end=253
  _globals['_APPLYPROFILEINTENTREQUEST']._serialized_start=256
  _globals['_APPLYPROFILEINTENTREQUEST']._serialized_end=433
  _globals['_PROVISIONINGSERVICE']._serialized_start=436
  _globals['_PROVISIONINGSERVICE']._serialized_end=919
# @@protoc_insertion_point(module_scope)
