# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from driver.v1 import runtime_service_pb2 as driver_dot_v1_dot_runtime__service__pb2
from driver.v1 import types_pb2 as driver_dot_v1_dot_types__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in driver/v1/runtime_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BackendNodeAction = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/BackendNodeAction',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.BackendNodeActionRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_runtime__service__pb2.BackendNodeSettingsResult.FromString,
                _registered_method=True)
        self.DecommissionNode = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/DecommissionNode',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.DecommissionNodeRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_runtime__service__pb2.DecommissionNodeResponse.FromString,
                _registered_method=True)
        self.ApplyBackendNodeSettings = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/ApplyBackendNodeSettings',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.ApplyBackendNodeSettingsRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
                _registered_method=True)
        self.PrepareBackendNode = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/PrepareBackendNode',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.PrepareBackendNodeRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_runtime__service__pb2.BackendNodeSettingsResult.FromString,
                _registered_method=True)
        self.RecoverBackendNodeSettings = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/RecoverBackendNodeSettings',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.ApplyBackendNodeSettingsRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_runtime__service__pb2.BackendNodeSettingsResult.FromString,
                _registered_method=True)
        self.ResolveBackendNodeSettings = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/ResolveBackendNodeSettings',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.ApplyBackendNodeSettingsRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_runtime__service__pb2.BackendNodeSettingsResult.FromString,
                _registered_method=True)
        self.GetBackendXrayPublic = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/GetBackendXrayPublic',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.GetBackendXrayPublicRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_runtime__service__pb2.BackendXrayPublicResult.FromString,
                _registered_method=True)
        self.RefreshAwgConfig = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/RefreshAwgConfig',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.RefreshAwgConfigRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_runtime__service__pb2.RefreshAwgConfigResponse.FromString,
                _registered_method=True)


class RuntimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BackendNodeAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecommissionNode(self, request, context):
        """Explicit backend-owned path; does not access legacy server/profile tables.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyBackendNodeSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareBackendNode(self, request, context):
        """Idempotent preparation of an already installed agent; no legacy registry read.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecoverBackendNodeSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveBackendNodeSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBackendXrayPublic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshAwgConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BackendNodeAction': grpc.unary_unary_rpc_method_handler(
                    servicer.BackendNodeAction,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.BackendNodeActionRequest.FromString,
                    response_serializer=driver_dot_v1_dot_runtime__service__pb2.BackendNodeSettingsResult.SerializeToString,
            ),
            'DecommissionNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DecommissionNode,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.DecommissionNodeRequest.FromString,
                    response_serializer=driver_dot_v1_dot_runtime__service__pb2.DecommissionNodeResponse.SerializeToString,
            ),
            'ApplyBackendNodeSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyBackendNodeSettings,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.ApplyBackendNodeSettingsRequest.FromString,
                    response_serializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.SerializeToString,
            ),
            'PrepareBackendNode': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareBackendNode,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.PrepareBackendNodeRequest.FromString,
                    response_serializer=driver_dot_v1_dot_runtime__service__pb2.BackendNodeSettingsResult.SerializeToString,
            ),
            'RecoverBackendNodeSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.RecoverBackendNodeSettings,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.ApplyBackendNodeSettingsRequest.FromString,
                    response_serializer=driver_dot_v1_dot_runtime__service__pb2.BackendNodeSettingsResult.SerializeToString,
            ),
            'ResolveBackendNodeSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveBackendNodeSettings,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.ApplyBackendNodeSettingsRequest.FromString,
                    response_serializer=driver_dot_v1_dot_runtime__service__pb2.BackendNodeSettingsResult.SerializeToString,
            ),
            'GetBackendXrayPublic': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBackendXrayPublic,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.GetBackendXrayPublicRequest.FromString,
                    response_serializer=driver_dot_v1_dot_runtime__service__pb2.BackendXrayPublicResult.SerializeToString,
            ),
            'RefreshAwgConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshAwgConfig,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.RefreshAwgConfigRequest.FromString,
                    response_serializer=driver_dot_v1_dot_runtime__service__pb2.RefreshAwgConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nodeplane.driver.v1.RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nodeplane.driver.v1.RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BackendNodeAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/BackendNodeAction',
            driver_dot_v1_dot_runtime__service__pb2.BackendNodeActionRequest.SerializeToString,
            driver_dot_v1_dot_runtime__service__pb2.BackendNodeSettingsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecommissionNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/DecommissionNode',
            driver_dot_v1_dot_runtime__service__pb2.DecommissionNodeRequest.SerializeToString,
            driver_dot_v1_dot_runtime__service__pb2.DecommissionNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyBackendNodeSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/ApplyBackendNodeSettings',
            driver_dot_v1_dot_runtime__service__pb2.ApplyBackendNodeSettingsRequest.SerializeToString,
            driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareBackendNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/PrepareBackendNode',
            driver_dot_v1_dot_runtime__service__pb2.PrepareBackendNodeRequest.SerializeToString,
            driver_dot_v1_dot_runtime__service__pb2.BackendNodeSettingsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecoverBackendNodeSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/RecoverBackendNodeSettings',
            driver_dot_v1_dot_runtime__service__pb2.ApplyBackendNodeSettingsRequest.SerializeToString,
            driver_dot_v1_dot_runtime__service__pb2.BackendNodeSettingsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveBackendNodeSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/ResolveBackendNodeSettings',
            driver_dot_v1_dot_runtime__service__pb2.ApplyBackendNodeSettingsRequest.SerializeToString,
            driver_dot_v1_dot_runtime__service__pb2.BackendNodeSettingsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBackendXrayPublic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/GetBackendXrayPublic',
            driver_dot_v1_dot_runtime__service__pb2.GetBackendXrayPublicRequest.SerializeToString,
            driver_dot_v1_dot_runtime__service__pb2.BackendXrayPublicResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshAwgConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/RefreshAwgConfig',
            driver_dot_v1_dot_runtime__service__pb2.RefreshAwgConfigRequest.SerializeToString,
            driver_dot_v1_dot_runtime__service__pb2.RefreshAwgConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
