# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: driver/v1/types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'driver/v1/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64river/v1/types.proto\x12\x13nodeplane.driver.v1\"O\n\x0b\x44riverError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\x12\x11\n\tretryable\x18\x04 \x01(\x08\".\n\x16StartOperationResponse\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\"@\n\x08XraySpec\x12\x14\n\x0cprofile_name\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x10\n\x08short_id\x18\x03 \x01(\t\"O\n\x0e\x44iagnosticItem\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x04 \x01(\t\"\x84\x02\n\tOperation\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x10\n\x08node_key\x18\x04 \x01(\t\x12\x14\n\x0cprofile_name\x18\x05 \x01(\t\x12\x12\n\nstarted_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t\x12\x13\n\x0b\x66inished_at\x18\x08 \x01(\t\x12\x18\n\x10progress_message\x18\t \x01(\t\x12/\n\x05\x65rror\x18\n \x01(\x0b\x32 .nodeplane.driver.v1.DriverError\x12\x13\n\x0bresult_json\x18\x0b \x01(\t\"U\n\x0eOperationEvent\x12\x31\n\toperation\x18\x01 \x01(\x0b\x32\x1e.nodeplane.driver.v1.Operation\x12\x10\n\x08log_line\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver.v1.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRIVERERROR']._serialized_start=46
  _globals['_DRIVERERROR']._serialized_end=125
  _globals['_STARTOPERATIONRESPONSE']._serialized_start=127
  _globals['_STARTOPERATIONRESPONSE']._serialized_end=173
  _globals['_XRAYSPEC']._serialized_start=175
  _globals['_XRAYSPEC']._serialized_end=239
  _globals['_DIAGNOSTICITEM']._serialized_start=241
  _globals['_DIAGNOSTICITEM']._serialized_end=320
  _globals['_OPERATION']._serialized_start=323
  _globals['_OPERATION']._serialized_end=583
  _globals['_OPERATIONEVENT']._serialized_start=585
  _globals['_OPERATIONEVENT']._serialized_end=670
# @@protoc_insertion_point(module_scope)
